"""email aliases

Revision ID: 2dd35a53714e
Revises: e7039807075c
Create Date: 2026-09-01 16:18:47.118888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd35a53714e'
down_revision = 'e7039807075c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('local_part', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('target_email', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_forwarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('forward_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('local_part', 'domain', name='uq_alias_local_domain')
    )
    with op.batch_alter_table('email_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_aliases_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_aliases_user_id'))

    op.drop_table('email_aliases')
    # ### end Alembic commands ###
