"""login ip restriction and session timeout

Revision ID: 2e9febfc05c3
Revises: 6113843a806a
Create Date: 2026-07-11 20:32:45.304261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e9febfc05c3'
down_revision = '6113843a806a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_login_ips', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('session_timeout_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('session_timeout_minutes')
        batch_op.drop_column('allowed_login_ips')

    # ### end Alembic commands ###
