"""invite quota, premium display customization

Revision ID: 358681d33cfc
Revises: 82f1652622a8
Create Date: 2026-07-06 21:39:31.710957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358681d33cfc'
down_revision = '82f1652622a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_quota', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('display_name_style', sa.String(length=16), server_default=sa.text("'default'"), nullable=False))
        batch_op.add_column(sa.Column('display_name_color', sa.String(length=9), server_default=sa.text("'#35E0C0'"), nullable=False))
        batch_op.add_column(sa.Column('display_name_gradient_color', sa.String(length=9), server_default=sa.text("'#F5C518'"), nullable=False))

    # Bestehende Nutzer mit dem alten can_invite=True bekommen ein
    # Start-Kontingent, statt ihre Berechtigung stillschweigend zu
    # verlieren -- 3 ist ein konservativer Startwert, ein Admin kann das
    # jederzeit nachjustieren.
    op.execute("UPDATE users SET invite_quota = 3 WHERE can_invite = 1")

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('can_invite')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_invite', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
        batch_op.drop_column('display_name_gradient_color')
        batch_op.drop_column('display_name_color')
        batch_op.drop_column('display_name_style')
        batch_op.drop_column('invite_quota')

    # ### end Alembic commands ###
