"""microsoft sso upn linking

Revision ID: 3c9946334e9e
Revises: 2e9febfc05c3
Create Date: 2026-07-28 18:12:00.094941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c9946334e9e'
down_revision = '2e9febfc05c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('microsoft_upn', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_users_microsoft_upn', ['microsoft_upn'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_microsoft_upn', type_='unique')
        batch_op.drop_column('microsoft_upn')

    # ### end Alembic commands ###
