"""captcha settings and login parallax option

Revision ID: 3d4aecb39f30
Revises: 3c9946334e9e
Create Date: 2026-08-19 20:05:46.722387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d4aecb39f30'
down_revision = '3c9946334e9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('captcha_provider', sa.String(length=16), server_default=sa.text("'none'"), nullable=False),
    sa.Column('captcha_enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('captcha_site_key', sa.String(length=255), nullable=True),
    sa.Column('captcha_secret_key', sa.String(length=255), nullable=True),
    sa.Column('captcha_on_login', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('captcha_on_register', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appearance_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parallax_enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearance_settings', schema=None) as batch_op:
        batch_op.drop_column('parallax_enabled')

    op.drop_table('security_settings')
    # ### end Alembic commands ###
