"""totp rotation timestamp

Revision ID: 6113843a806a
Revises: d556ab822d6d
Create Date: 2026-07-10 14:57:35.520352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6113843a806a'
down_revision = 'd556ab822d6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_rotated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('totp_rotated_at')

    # ### end Alembic commands ###
