"""parallax strength

Revision ID: 62da7847d9bf
Revises: 3d4aecb39f30
Create Date: 2026-08-19 20:59:59.825025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62da7847d9bf'
down_revision = '3d4aecb39f30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearance_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parallax_strength', sa.Float(), server_default=sa.text('(1.0)'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearance_settings', schema=None) as batch_op:
        batch_op.drop_column('parallax_strength')

    # ### end Alembic commands ###
