"""shoutbox auto clear tracking

Revision ID: 82f1652622a8
Revises: aa1c8e049141
Create Date: 2026-07-06 18:25:22.270872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f1652622a8'
down_revision = 'aa1c8e049141'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearance_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_last_cleared_date', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appearance_settings', schema=None) as batch_op:
        batch_op.drop_column('chat_last_cleared_date')

    # ### end Alembic commands ###
