"""adguard settings

Revision ID: a8c6651a7e5e
Revises: c21eae08527f
Create Date: 2026-09-02 18:00:29.557225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c6651a7e5e'
down_revision = 'c21eae08527f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adguard_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('configured', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('encrypted_password', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adguard_settings')
    # ### end Alembic commands ###
