"""audit log, premium fields, invite self-service, appearance transparency

Revision ID: aa1c8e049141
Revises: 1b1325407b99
Create Date: 2026-07-06 17:26:21.069444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa1c8e049141'
down_revision = '1b1325407b99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entries_event_type'), ['event_type'], unique=False)

    with op.batch_alter_table('appearance_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_opacity_percent', sa.Integer(), server_default=sa.text('(90)'), nullable=False))
        batch_op.add_column(sa.Column('form_blur_px', sa.Integer(), server_default=sa.text('4'), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_invite', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('is_premium', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('premium_badge_color', sa.String(length=9), server_default=sa.text("'#F5C518'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('premium_badge_color')
        batch_op.drop_column('is_premium')
        batch_op.drop_column('can_invite')

    with op.batch_alter_table('appearance_settings', schema=None) as batch_op:
        batch_op.drop_column('form_blur_px')
        batch_op.drop_column('form_opacity_percent')

    with op.batch_alter_table('audit_log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entries_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entries_created_at'))

    op.drop_table('audit_log_entries')
    # ### end Alembic commands ###
