"""one time secret max views

Revision ID: c21eae08527f
Revises: 2dd35a53714e
Create Date: 2026-09-01 17:37:20.897840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c21eae08527f'
down_revision = '2dd35a53714e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('one_time_secrets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_views', sa.Integer(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('view_count', sa.Integer(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('one_time_secrets', schema=None) as batch_op:
        batch_op.drop_column('view_count')
        batch_op.drop_column('max_views')

    # ### end Alembic commands ###
