"""feature request tags

Revision ID: d556ab822d6d
Revises: fa4c7e53945d
Create Date: 2026-07-07 18:55:26.033645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd556ab822d6d'
down_revision = 'fa4c7e53945d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=200), server_default=sa.text("('')"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature_requests', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
