"""one time secrets

Revision ID: e7039807075c
Revises: f82b85bf7804
Create Date: 2026-09-01 12:43:02.394076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7039807075c'
down_revision = 'f82b85bf7804'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('one_time_secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('creator_user_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_content', sa.String(length=16384), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('one_time_secrets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_one_time_secrets_creator_user_id'), ['creator_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_one_time_secrets_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_one_time_secrets_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('one_time_secrets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_one_time_secrets_token'))
        batch_op.drop_index(batch_op.f('ix_one_time_secrets_expires_at'))
        batch_op.drop_index(batch_op.f('ix_one_time_secrets_creator_user_id'))

    op.drop_table('one_time_secrets')
    # ### end Alembic commands ###
