"""saved ssh connections

Revision ID: f82b85bf7804
Revises: 62da7847d9bf
Create Date: 2026-08-31 19:44:22.192142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f82b85bf7804'
down_revision = '62da7847d9bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_ssh_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), server_default=sa.text('(22)'), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('auth_method', sa.String(length=16), server_default=sa.text("'none'"), nullable=False),
    sa.Column('encrypted_secret', sa.String(length=8192), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'label', name='uq_ssh_conn_user_label')
    )
    with op.batch_alter_table('saved_ssh_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_ssh_connections_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_ssh_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_ssh_connections_user_id'))

    op.drop_table('saved_ssh_connections')
    # ### end Alembic commands ###
