"""feature request downvote support

Revision ID: fa4c7e53945d
Revises: 358681d33cfc
Create Date: 2026-07-06 22:13:40.714320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa4c7e53945d'
down_revision = '358681d33cfc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature_request_votes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vote_value', sa.Integer(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature_request_votes', schema=None) as batch_op:
        batch_op.drop_column('vote_value')

    # ### end Alembic commands ###
